Repository PublicFreeSuffix/PublicFreeSuffix, pull requests merged in 2025-07, with the labels that each got.

#1 Registration: sky.no.kg
  whois/sky.no.kg.json
Labels: Pending Setup

#3 Registration: pax.no.kg.json
  whois/pax.no.kg.json
Labels: Pending Setup

#14 Registration: migration-test.no.kg
  whois/migration-test.no.kg.json
Labels: validation-passed

#16 Registration: ink.no.kg
  whois/ink.no.kg.json
Labels: validation-passed

#15 Remove: migration-test.no.kg
  whois/ink.no.kg.json
Labels: validation-passed

#19 Update: ink.no.kg
  whois/ink.no.kg.json
Labels: validation-passed

#13 Remove: pax.no.kg
  whois/pax.no.kg.json
Labels: validation-passed

#33 Registration: hub.no.kg
  whois/hub.no.kg.json
Labels: validation-passed

#38 Registration: niu.htu.edu.kg
  whois/niu.htu.edu.kg.json
Labels: validation-passed

#40 Registration: halo.htu.edu.kg
  whois/halo.htu.edu.kg.json
Labels: validation-passed

#48 Registration: brick.htu.edu.kg
  whois/brick.htu.edu.kg.json
Labels: validation-passed

#51 Registration: lgccrush.htu.edu.kg
  whois/lgccrush.htu.edu.kg.json
Labels: validation-passed

#58 Update: summer.htu.edu.kg
  whois/summer.htu.edu.kg.json
Labels: validation-passed

#60 Update: ikun9527.htu.edu.kg
  whois/ikun9527.htu.edu.kg.json
Labels: validation-passed

#63 Registration: disco.htu.edu.kg
  whois/disco.htu.edu.kg.json
Labels: validation-passed

#70 Registration: mjcaoo.htu.edu.kg
  whois/mjcaoo.htu.edu.kg.json
Labels: validation-passed

#71 Registration: yes.no.kg
  whois/yes.no.kg.json
Labels: validation-passed

#68 Registration: crystalccc.no.kg
  whois/crystalccc.no.kg.json
Labels: validation-passed

#75 Registration: eee.htu.edu.kg
  whois/eee.htu.edu.kg.json
Labels: validation-passed

#77 Update: ikun9527.htu.edu.kg
  whois/ikun9527.htu.edu.kg.json
Labels: validation-passed

#69 Registration: sop.htu.edu.kg
  whois/sop.htu.edu.kg.json
Labels: Pending User Confirmation, validation-passed

#92 Registration: ztsc.htu.edu.kg
  whois/ztsc.htu.edu.kg.json
Labels: validation-passed

#91 Registration: dev.htu.edu.kg
  whois/dev.htu.edu.kg.json
Labels: validation-passed

#89 Registration: yexi.htu.edu.kg
  whois/yexi.htu.edu.kg.json
Labels: validation-passed

#84 Registration: qby.htu.edu.kg
  whois/qby.htu.edu.kg.json
Labels: validation-passed

#79 Registration: ccc007.htu.edu.kg
  whois/ccc007.htu.edu.kg.json
Labels: validation-passed

#121 Registration: nikaidouyui.htu.edu.kg
  whois/nikaidouyui.htu.edu.kg.json
Labels: validation-passed

#116 Registration: furina.no.kg
  whois/furina.no.kg.json
Labels: validation-passed

#115 Registration: xiaodouli.no.kg
  whois/xiaodouli.no.kg.json
Labels: validation-passed

#99 Registration: mia.no.kg
  whois/mia.no.kg.json
Labels: validation-passed

#98 Update: qby.htu.edu.kg
  whois/qby.htu.edu.kg.json
Labels: validation-passed

#131 Registration: pr-autest.no.kg
  whois/pr-autest.no.kg.json
Labels: validation-passed

#133 Update: pr-autest.no.kg
  whois/pr-autest.no.kg.json
Labels: validation-passed

#134 Registration: xju.htu.edu.kg
  whois/xju.htu.edu.kg.json
Labels: validation-passed

#140 Registration: autoremove.no.kg
  whois/autoremove.no.kg.json
Labels: validation-passed

#142 Remove: autoremove.no.kg
  whois/autoremove.no.kg.json
Labels: validation-passed

#129 Registration: cnus.htu.edu.kg
  whois/cnus.htu.edu.kg.json
Labels: validation-passed

#144 Update: mails.htu.edu.kg
  whois/mails.htu.edu.kg.json
Labels: validation-passed

#149 Update: mails.htu.edu.kg
  whois/mails.htu.edu.kg.json
Labels: validation-passed

#151 Registration: say.no.kg
  whois/say.no.kg.json
Labels: validation-passed

#130 Registration: ikula.htu.edu.kg
  whois/ikula.htu.edu.kg.json
Labels: validation-passed

#128 Update: yexi.htu.edu.kg
  whois/yexi.htu.edu.kg.json
Labels: validation-passed

#153 Registration: stu.htu.edu.kg
  whois/stu.htu.edu.kg.json
Labels: validation-passed

#156 Registration: lzm.no.kg
  whois/lzm.no.kg.json
Labels: validation-passed

#163 Registration: win.htu.edu.kg
  whois/win.htu.edu.kg.json
Labels: validation-passed

#165 Registration: ccciyo.htu.edu.kg
  whois/ccciyo.htu.edu.kg.json
Labels: validation-passed

#170 Registration: cat.htu.edu.kg
  whois/cat.htu.edu.kg.json
Labels: validation-passed

#172 Registration: ooh.no.kg
  whois/ooh.no.kg.json
Labels: validation-passed

#174 Registration: master.htu.edu.kg
  whois/master.htu.edu.kg.json
Labels: validation-passed

#175 Update: yexi.htu.edu.kg
  whois/yexi.htu.edu.kg.json
Labels: validation-passed

#179 Registration: lklkl.htu.edu.kg
  whois/lklkl.htu.edu.kg.json
Labels: validation-passed

#180 Update: cat.htu.edu.kg
  whois/cat.htu.edu.kg.json
Labels: validation-passed

#187 Update: cat.htu.edu.kg
  whois/cat.htu.edu.kg.json
Labels: validation-passed

#185 Registration: cor.no.kg
  whois/cor.no.kg.json
Labels: validation-passed

#125 Registration: edu.htu.edu.kg
  whois/edu.htu.edu.kg.json
Labels: validation-passed

#195 Registration: kyc.no.kg
  whois/kyc.no.kg.json
Labels: validation-passed

#196 Update: cat.htu.edu.kg
  whois/cat.htu.edu.kg.json
Labels: validation-passed

#202 Update: xju.htu.edu.kg
  whois/xju.htu.edu.kg.json
Labels: validation-passed

#201 Registration: ive.htu.edu.kg
  whois/ive.htu.edu.kg.json
Labels: validation-passed

#211 Registration: ch6vip.htu.edu.kg
  whois/ch6vip.htu.edu.kg.json
Labels: validation-passed

#214 Update: octo.htu.edu.kg
  whois/octo.htu.edu.kg.json
Labels: validation-passed

#215 Update: idea.htu.edu.kg
  whois/idea.htu.edu.kg.json
Labels: validation-passed

#217 Registration: ndus.htu.edu.kg
  whois/ndus.htu.edu.kg.json
Labels: validation-passed

#218 Registration: yang.no.kg
  whois/yang.no.kg.json
Labels: validation-passed

#220 Registration: plus.htu.edu.kg
  whois/plus.htu.edu.kg.json
Labels: validation-passed

#219 Registration: linuxdo.htu.edu.kg
  whois/linuxdo.htu.edu.kg.json
Labels: validation-passed

#223 Remove: cnus.htu.edu.kg
  whois/cnus.htu.edu.kg.json
Labels: validation-passed

#225 Registration: one.no.kg
  whois/one.no.kg.json
Labels: validation-passed

#228 Registration: kaya.no.kg
  whois/kaya.no.kg.json
Labels: validation-passed

#232 Registration: fol.htu.edu.kg
  whois/fol.htu.edu.kg.json
Labels: validation-passed

#236 Registration: kali.htu.edu.kg
  whois/kali.htu.edu.kg.json
Labels: validation-passed

#239 Registration: fast.tun.re
  whois/fast.tun.re.json
Labels: validation-passed

#237 Update: xiaodouli.no.kg
  whois/xiaodouli.no.kg.json
Labels: validation-passed

#240 Registration: zero.no.kg
  whois/zero.no.kg.json
Labels: validation-passed

#243 Registration: phaedrus.htu.edu.kg
  whois/phaedrus.htu.edu.kg.json
Labels: validation-passed

#244 Registration: misc.no.kg
  whois/misc.no.kg.json
Labels: validation-passed

#252 Registration: cnb.no.kg
  whois/cnb.no.kg.json
Labels: validation-passed

#254 Update: cnb.no.kg
  whois/cnb.no.kg.json
Labels: validation-passed

#255 Registration: edu.tun.re
  whois/edu.tun.re.json
Labels: validation-passed

#257 Registration: taocrypt.no.kg
  whois/taocrypt.no.kg.json
Labels: validation-passed

#263 Registration: edu.nastu.net
  whois/edu.nastu.net.json
Labels: validation-passed

#265 Registration: 10s.6ti.net
  whois/10s.6ti.net.json
Labels: validation-passed

#271 Registration: taocrypt.6ti.net
  whois/taocrypt.6ti.net.json
Labels: validation-passed

#275 Registration: stormocean.no.kg
  whois/stormocean.no.kg.json
Labels: validation-passed

#279 Registration: fap.no.kg
  whois/fap.no.kg.json
Labels: validation-passed

#281 Update: fap.no.kg
  whois/fap.no.kg.json
Labels: validation-passed

#283 Registration: katsu.nastu.net
  whois/katsu.nastu.net.json
Labels: validation-passed

#284 Registration: nil.no.kg
  whois/nil.no.kg.json
Labels: validation-passed

#292 Update: 525.tun.re
  whois/525.tun.re.json
Labels: validation-passed
